/*
Deployment script for Formulario Contactos

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "Formulario Contactos"
:setvar DefaultFilePrefix "Contac"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[Contactos]...';


GO
CREATE TABLE [dbo].[Contactos] (
    [Id]        INT            IDENTITY (1, 1) NOT NULL,
    [Nombre]    NVARCHAR (50)  NOT NULL,
    [Apellido]  NVARCHAR (50)  NOT NULL,
    [Telefono]  NVARCHAR (20)  NULL,
    [Direccion] NVARCHAR (100) NULL,
    CONSTRAINT [PK_Contactos] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating Procedure [dbo].[ActualizarContacto]...';


GO
CREATE PROCEDURE ActualizarContacto
    @Id INT,
    @Nombre NVARCHAR(50),
    @Apellido NVARCHAR(50),
    @Telefono NVARCHAR(20),
    @Direccion NVARCHAR(100)
AS
BEGIN
    UPDATE Contactos
    SET Nombre = @Nombre,
        Apellido = @Apellido,
        Telefono = @Telefono,
        Direccion = @Direccion
    WHERE Id = @Id;
END
GO
PRINT N'Creating Procedure [dbo].[BorrarContacto]...';


GO
CREATE PROCEDURE BorrarContacto
    @Id INT
AS
BEGIN
    DELETE FROM Contactos WHERE Id = @Id;
END
GO
PRINT N'Creating Procedure [dbo].[GetContactos]...';


GO
CREATE PROCEDURE GetContactos
    @Search NVARCHAR(50) = NULL
AS
BEGIN
    SET NOCOUNT ON;
    DECLARE @sql NVARCHAR(MAX) = N'
    SELECT Id, Nombre, Apellido, Telefono, Direccion 
    FROM Contactos ';

    IF @Search IS NOT NULL
    BEGIN
        SET @sql = @sql + ' WHERE Nombre LIKE @Search OR Apellido LIKE @Search OR Telefono LIKE @Search OR Direccion LIKE @Search ';
    END

    EXEC sp_executesql @sql, N'@Search NVARCHAR(50)', @Search;
END
GO
PRINT N'Creating Procedure [dbo].[InsertarContacto]...';


GO
CREATE PROCEDURE InsertarContacto
    @Nombre NVARCHAR(50),
    @Apellido NVARCHAR(50),
    @Telefono NVARCHAR(20),
    @Direccion NVARCHAR(100)
AS
BEGIN
    INSERT INTO Contactos (Nombre, Apellido, Telefono, Direccion)
    VALUES (@Nombre, @Apellido, @Telefono, @Direccion);
END
GO
PRINT N'Update complete.';


GO
